// Feature mapping configuration
const FEATURE_MAP = {
    "_config": { "vmax_threshold": 4.0 },
    "DATUM": "rm",
    "PNR": "rm",
    "Age": "keep",
    "Sex": "keep",
    "NAMN": "rm",
    "AVD": "rm",
    "LÄNGD": 2.0,
    "VIKT": 2.0,
    "BMA/LÄK": "rm",
    "BMA_eko": "rm",
    "INDIK": "indik",
    "BTS": 2.0,
    "BTD": 2.0,
    "PULS": 2.0,
    "Vilo-EKG (när detta finns)": "keep",
    "Förmaksflimmer": "keep",
    "Sept": "keep",
    "Bakv": "keep",
    "Diast": 1.0,
    "Syst": 1.0,
    "AV-plan": "keep",
    "EF_typ": "rm",
    "EF": 2.0,
    "GLS": 1.0,
    "VK_4k": "rm",
    "Volym": 1.0,
    "HK_parast": 1.0,
    "HK_4K": 2.0,
    "TAPSE": 1.0,
    "AORTA": 1.0,
    "Aorta_asc": 1.0,
    "VÄ FÖRM.": "rm",
    "VF_4K": 1.0,
    "VF_Volym": 2.0,
    "HF_4K": 1.0,
    "Mitralis Klaffprotes": "rm",
    "E (cm/s)": 1.0,
    "A (cm/s)": 1.0,
    "E_dec_ms": 3.0,
    "VTI (cm)": 1.0,
    "Medeltryck": 1.0,
    "E' (cm/s)": 0.1,
    "A' (cm/s)": 0.1,
    "S'": 0.1,
    "E'_lat": 0.1,
    "LUNGVEN S/D": 0.1,
    "TRICUSP": 0.2,
    "HF-tryck": 2.0,
    "LVOTVmax": "rm",
    "LVOTI (cm)": 1.0,
    "LVOT Diam": 1.0,
    "AORTAKlaffprotes": "rm",
    "Vmax (m/s)": 0.3,
    "VTI (cm).1": 1.0,
    "Medeltryck (mmHg)": 1.0,
    "PULMVmax (m/s)": 0.1,
    "Band #": "rm",
    "Position": "rm",
    "VKForm": "keep",
    "VKVäggrörlighet": "keep",
    "VKGlobal syst (visuell bedömn)": "keep",
    "Hö kammare": "keep",
    "Hö förmak": "keep",
    "Aorta": "keep",
    "Mitr (Främre)": "keep",
    "Mitr (Bakre)": "keep",
    "Tricusp": "keep",
    "Pulm": "keep",
    "AIINSInt": "keep",
    "AIUtbredn": "keep",
    "MIInt": "keep",
    "MIUtbredn": "keep",
    "PISA (mm)": "keep",
    "TIInt": "keep",
    "Utbredn": "keep",
    "PIInt": "keep",
    "PIUtbredn": "keep",
    "VF storlek": "keep",
    "Övrigt": "keep"
};
const VMAX_THRESHOLD = FEATURE_MAP._config.vmax_threshold;